### ISSUE TITLE
有些比赛的数据中没有返回英雄伤害，暂时不知道为啥

### ISSUE THREAD

**Issue by GoCross** [Inv0k3r/DOTA2_Bot#5]
`{
	'account_id': 136221615,
	'player_slot': 0,
	'hero_id': 43,
	'item_0': 100,
	'item_1': 119,
	'item_2': 77,
	'item_3': 108,
	'item_4': 235,
	'item_5': 48,
	'backpack_0': 216,
	'backpack_1': 0,
	'backpack_2': 0,
	'item_neutral': 358,
	'kills': 11,
	'deaths': 3,
	'assists': 10,
	'leaver_status': 0,
	'last_hits': 282,
	'denies': 13,
	'gold_per_min': 613,
	'xp_per_min': 753,
	'level': 24
}
`
数据大概长这样
建议加上`setdefault`或者异常处理

**Comment by phoneixSH** [comment]
V社在比赛超过2个月后会删除 技能加点信息和英雄伤害等信息 ,只留下基本比赛信息
不过也可能是这把比赛压根没打起来就秒了

**Comment by GoCross** [comment]
> V社在比赛超过2个月后会删除 技能加点信息和英雄伤害等信息 ,只留下基本比赛信息
> 不过也可能是这把比赛压根没打起来就秒了

原来如此，这是我测试的时候搞了一下最近比赛数据，都是2个月以上的。
